### ISSUE TITLE
gf启动报错

### ISSUE THREAD

**Issue by lwk5213** [gogf/swagger#1]
# github.com/gogf/gf-swagger/swagger
vendor\github.com\gogf\gf-swagger\swagger\swagger.go:76:5: s.Logger undefined (type *ghttp.Server has no field or method Logger)

**Comment by houseme** [comment]
https://github.com/gogf/gf-swagger/pull/2

**Comment by gqcn** [comment]
@lwk5213 @houseme 功能已发布可用，更新到最新的`gf-swagger`和`gf`版本试试。
