### ISSUE TITLE
 swag 1.6.6版本  swag init -o 选项失效导致生成出错

### ISSUE THREAD

**Issue by tky753** [gogf/swagger#5]
[link](https://github.com/swaggo/swag/issues/705#issuecomment-632536163)

**Comment by SOVLOOKUP** [comment]
和你一样 解决否

**Comment by gqcn** [comment]
@tky753 This plugin does not depend on swaggo, but a plugin for gf. BTW the gf-cli uses swaggo as third party binary without any imports into codes.
